// <auto-generated />
namespace Periodical.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class publicationubdateaddfieldTimesInYear : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(publicationubdateaddfieldTimesInYear));
        
        string IMigrationMetadata.Id
        {
            get { return "201509101639476_publication-ubdate-add-field-TimesInYear"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
